import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import PageHeader from "@/components/PageHeader";
import PageFooter from "@/components/PageFooter";
import PageIntro from "@/components/PageIntro";
import CallToAction from "@/components/CallToAction";

export const metadata: Metadata = { title: "Capabilities", description: "See what Diction can help implement after the strategy is clear—without packages, menus or disconnected deliverables." };

const capabilities = [
  { number: "01", title: "Positioning & narrative", body: "Clarify the expertise association, audience, problem, point of view and language every platform should reinforce.", outputs: ["Positioning system", "Narrative architecture", "Homepage message", "Founder story"] },
  { number: "02", title: "Authority content", body: "Translate expertise into themes, evidence, stories and repeatable formats that make thinking visible.", outputs: ["Editorial strategy", "Authority themes", "Content systems", "Thought-leadership formats"] },
  { number: "03", title: "Trust experience", body: "Design the owned experience around clarity, proof, human credibility and relevant next actions.", outputs: ["Website strategy", "Information architecture", "UX direction", "Conversion journeys"] },
  { number: "04", title: "Platform integration", body: "Connect website, profiles, content, lead capture and follow-up so every part contributes to one recognisable identity.", outputs: ["Platform roles", "Profile alignment", "Lead journeys", "Nurture architecture"] },
];

export default function CapabilitiesPage() {
  return (
    <main className="overflow-hidden bg-[#050505] text-white"><PageHeader /><PageIntro eyebrow="Capabilities" title="Implementation after the strategy is clear." description="Diction can help shape and build the parts of a digital authority ecosystem. The work is scoped around the gap and desired opportunity—not a menu of disconnected packages." primary={{ label: "Learn the system first", href: "/known" }} secondary={{ label: "About Diction", href: "/about" }} image={{ src: "/founder-profile-left.png", alt: "Diction founder in profile wearing a black kurta" }} />
      <section className="section-pad border-b border-white/8"><div className="mx-auto max-w-[1280px] px-6 md:px-10"><div className="grid gap-8 lg:grid-cols-[1fr_360px] lg:items-end"><h2 className="editorial-heading">Four capabilities. <span className="text-white/38">One connected system.</span></h2><p className="text-base leading-relaxed text-white/46">Each capability solves a different part of the same recognition problem. Strategy determines which one comes first.</p></div><div className="mt-14 grid gap-4 lg:grid-cols-2">{capabilities.map((capability, index) => <article key={capability.title} className={`flex min-h-[420px] flex-col rounded-[1.35rem] border p-8 md:p-10 ${index === 3 ? "border-[#2f7cf6] bg-[#2f7cf6]" : "border-white/13 bg-white/[0.03]"}`}><span className="text-xs font-bold text-[#8db7ff]">{capability.number}</span><h2 className="mt-7 max-w-[12ch] text-4xl font-semibold leading-[0.98] tracking-[-0.05em]">{capability.title}</h2><p className="mt-5 max-w-xl text-sm leading-relaxed text-white/54">{capability.body}</p><ul className="mt-auto grid gap-3 border-t border-white/12 pt-7 text-sm font-semibold text-white/72 sm:grid-cols-2">{capability.outputs.map((output) => <li key={output}>{output}</li>)}</ul></article>)}</div></div></section>
      <section className="surface-inset relative overflow-hidden bg-[#0b0b0d] px-6 py-20 text-white md:px-10 md:py-28"><div className="absolute inset-y-0 right-0 hidden w-[46%] bg-[url('/diction-system-visual.png')] bg-cover bg-center opacity-20 lg:block" /><div className="absolute inset-0 bg-gradient-to-r from-[#0b0b0d] via-[#0b0b0d]/94 to-[#0b0b0d]/66" /><div className="relative mx-auto max-w-[1180px]"><div className="grid gap-10 lg:grid-cols-[1fr_360px] lg:items-end"><div><p className="section-label text-[#8db7ff]">How an engagement begins</p><h2 className="editorial-heading mt-7">Diagnose. Decide. Then design the right scope.</h2></div><p className="text-sm leading-relaxed text-white/42">Diction does not publish fixed packages or promise predetermined outcomes. Scope, timing and fit depend on the diagnosis and the capacity to implement well.</p></div><ol className="mt-12 grid gap-4 sm:grid-cols-2">{[["01", "Diagnose", "Locate the gap currently limiting the wider system."], ["02", "Prioritise", "Choose the smallest focused sequence capable of creating meaningful change."], ["03", "Implement", "Build the agreed parts with the founder or expert actively involved."], ["04", "Integrate", "Make the new work reinforce every important platform and next step."]].map(([number, title, body]) => <li key={title} className="rounded-[1.5rem] border border-white/12 bg-black/38 p-7 backdrop-blur-sm"><span className="text-xs font-bold text-[#8db7ff]">{number}</span><h3 className="mt-7 text-2xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-relaxed text-white/50">{body}</p></li>)}</ol><Link href="/success-stories" className="mt-9 inline-flex items-center gap-2 text-sm font-semibold text-[#8db7ff]">See the process in context <ArrowRight size={14} /></Link></div></section>
      <CallToAction title="Understand your priority before discussing implementation." body="KNOWN gives you the framework and 90-day build order to make a better decision about what to do yourself and where support creates leverage." /><PageFooter /></main>
  );
}
