import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import PageHeader from "@/components/PageHeader";
import PageFooter from "@/components/PageFooter";
import PageIntro from "@/components/PageIntro";
import CallToAction from "@/components/CallToAction";

export const metadata: Metadata = { title: "Success Stories", description: "Explore the kinds of founder and expert transformation Diction is designed to create, with process before claims." };

const patterns = [
  { type: "Founder authority system", before: "Credible work, broad messaging and a website organised around services.", shift: "A single expertise association, clear audience language and proof connected to a relevant next step.", system: "Positioning → founder story → website trust journey → authority content." },
  { type: "Consultant positioning reset", before: "Strong delivery, interchangeable category language and content without a point of view.", shift: "A distinct perspective made visible through repeated ideas, examples and a recognisable voice.", system: "Positioning → point-of-view themes → evidence library → content formats." },
  { type: "Expert platform alignment", before: "Useful profiles and assets that each communicate a slightly different identity.", shift: "One position and one visual-verbal system repeated across the website, profiles and follow-up.", system: "Platform roles → profile alignment → lead journey → nurture path." },
];

export default function SuccessStoriesPage() {
  return (
    <main className="overflow-hidden bg-[#050505] text-white"><PageHeader /><PageIntro eyebrow="Success stories" title="What changes when the system connects." description="Diction evaluates progress through clarity, recognition, trust and better opportunity pathways—not through isolated deliverables or attention metrics alone." primary={{ label: "See the process", href: "#stories" }} secondary={{ label: "Explore capabilities", href: "/capabilities" }} image={{ src: "/founder-profile-right.png", alt: "Diction founder smiling in profile" }} />
      <section className="section-pad px-6 md:px-10"><div className="mx-auto grid max-w-[1280px] gap-12 rounded-[2.2rem] bg-white p-5 text-[#171717] lg:grid-cols-[1fr_1fr] lg:items-center lg:p-8"><div className="relative aspect-[4/3] overflow-hidden rounded-[1.8rem]"><Image src="/stock-masterclass-stage.jpg" alt="Speaker sharing ideas with a live audience" fill className="object-cover" sizes="(min-width: 1024px) 50vw, 100vw" /></div><div className="p-3 md:p-7"><p className="section-label text-[#2f62b6]">Proof with context</p><h2 className="editorial-heading mt-7">Process before performance claims.</h2><p className="body-large mt-7 text-black/52">The story that matters is not “we made a website.” It is what was unclear before, which gap constrained the system, what changed and how the new experience supports recognition or opportunity.</p><p className="mt-6 rounded-[1.4rem] bg-[#e9eef8] p-5 text-sm leading-relaxed text-black/50">Verified, named client stories and metrics should only be published with permission and source evidence.</p><p className="mt-4 text-[10px] uppercase tracking-[0.1em] text-black/32">Stock photography: Matheus Bertelli / Pexels</p></div></div></section>
      <section id="stories" className="section-pad border-b border-white/8 pt-0"><div className="mx-auto max-w-[1280px] px-6 md:px-10"><div className="grid gap-8 lg:grid-cols-[1fr_360px] lg:items-end"><div><h2 className="editorial-heading">Transformation patterns. <span className="text-white/38">Before, shift, system.</span></h2><p className="mt-6 max-w-2xl text-sm leading-relaxed text-white/46">These are not testimonials or performance claims. They show the before-to-after logic a documented case study should make visible.</p></div><Link href="/capabilities" className="inline-flex items-center gap-2 text-sm font-semibold text-[#8db7ff] lg:justify-self-end">See what Diction can implement <ArrowRight size={14} /></Link></div><div className="mt-14 grid gap-4 lg:grid-cols-3">{patterns.map((pattern, index) => <article key={pattern.type} className={`flex min-h-[520px] flex-col rounded-[1.35rem] border p-8 ${index === 1 ? "border-[#2f7cf6] bg-[#2f7cf6]" : "border-white/13 bg-white/[0.03]"}`}><span className="text-[#8db7ff]">0{index + 1}</span><h3 className="mt-7 text-3xl font-semibold leading-[1] tracking-[-0.05em]">{pattern.type}</h3><div className="mt-auto"><p className="text-xs font-semibold text-white/38">Before → shift</p><p className="mt-3 text-sm leading-relaxed text-white/48">{pattern.before}</p><p className="mt-4 text-sm font-semibold leading-relaxed text-[#b8d0ff]">{pattern.shift}</p><p className="mt-7 border-t border-white/12 pt-5 text-sm font-semibold text-white/76">{pattern.system}</p></div></article>)}</div></div></section>
      <CallToAction title="Your gap should determine the work—not the other way around." body="Use the Digital Presence Score to identify the part of your system that needs attention first." href="/tools/digital-presence-score" label="Discover my score" /><PageFooter /></main>
  );
}
