import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import PageHeader from "@/components/PageHeader";
import PageFooter from "@/components/PageFooter";
import PageIntro from "@/components/PageIntro";
import CallToAction from "@/components/CallToAction";
import { insights } from "@/lib/siteContent";

export const metadata: Metadata = { title: "Insights", description: "Practical thinking on positioning, authority, trust, websites and AI-era digital presence." };

export default function InsightsPage() {
  return <main className="overflow-hidden bg-[#050505] text-white"><PageHeader /><PageIntro eyebrow="Diction insights" title="Clear thinking for a recognisable presence." description="Practical essays for founders and experts who want to build authority, trust and opportunity without chasing every platform or trend." primary={{ label: "Read the latest insight", href: `/insights/${insights[0].slug}` }} secondary={{ label: "Use a free tool", href: "/tools" }} image={{ src: "/founder-outdoor.png", alt: "Close portrait of the Diction founder outdoors" }} /><section className="section-pad border-b border-white/8 pt-0"><div className="mx-auto max-w-[1280px] px-6 md:px-10"><div className="grid gap-8 lg:grid-cols-[1fr_340px] lg:items-end"><h2 className="editorial-heading">Latest thinking. <span className="text-white/38">Built to be useful.</span></h2><p className="text-base leading-relaxed text-white/46">Short, practical essays on the decisions that make expertise easier to understand, trust and choose.</p></div><div className="mt-14 grid gap-4 lg:grid-cols-3">{insights.map((insight, index) => <Link key={insight.slug} href={`/insights/${insight.slug}`} className={`group flex min-h-[560px] flex-col overflow-hidden rounded-[1.35rem] border transition-colors hover:border-white/24 ${index === 2 ? "border-[#2f7cf6] bg-[#2f7cf6]" : "border-white/13 bg-white/[0.03]"}`}><div className="relative aspect-[16/10] overflow-hidden border-b border-white/10"><Image src="/diction-story-insights.png" alt="" fill className="object-cover transition-transform duration-700 group-hover:scale-[1.03]" style={{ objectPosition: `${20 + index * 30}% center` }} sizes="(min-width: 1024px) 33vw, 100vw" /><div className="absolute inset-0 bg-gradient-to-t from-black/42 via-transparent to-transparent" /></div><div className="flex flex-1 flex-col p-8"><div className="flex items-center justify-between gap-4"><p className="text-xs font-semibold text-[#8db7ff]">{insight.category}</p><p className="text-xs text-white/36">{insight.readTime}</p></div><h2 className="mt-8 text-3xl font-semibold leading-[1.02] tracking-[-0.05em]">{insight.title}</h2><p className="mt-5 text-sm leading-relaxed text-white/52">{insight.excerpt}</p><span className="mt-auto inline-flex items-center gap-2 pt-8 text-sm font-semibold">Read insight <ArrowRight size={16} className="transition-transform group-hover:translate-x-1" /></span></div></Link>)}</div></div></section><CallToAction title="Reading creates context. Diagnosis creates priority." body="Use a free Diction tool to understand which part of your digital presence deserves attention first." href="/tools" label="Explore free tools" /><PageFooter /></main>;
}
